callFunction0 pointer param portability to 32-bit system
qoretechnologies/module-jni pull request #17
Opened 2017-01-22 10:22 UTC by tmandys

2017-01-22 15:21 UTC, davidnich commented
@tmandys please assign to me when ready to merge

2017-01-22 15:22 UTC, davidnich requested changes

2017-01-22 15:22 UTC, davidnich commented on docs/mainpage.dox.tmpl
> +    - fixed callFunction0 issue when running at 32-bit system
please remove this release note - this is unreleased code - release notes are meant to document changes between releases

2017-01-22 16:30 UTC, merged

2017-01-23 09:53 UTC, omusil24 commented
@tmandys Can you explain why passing a simple pointer doesn't work?

2017-01-23 09:59 UTC, tmandys commented
Because parameter is defined as jlong (64bit) but (Class*) pointer is 32-bit at 32bit OS so the calling function stack prepared by java does not correrspond to stack expecting by C++. I.e. use jlong parameter and retype to pointer in next step. It was already used in another function so it is not my invention.

2017-01-23 10:02 UTC, omusil24 commented
Ok. Thank you.